/**
 *
 * *  Error Constants
 *
 */

// Error codes
export const ERROR_CODES = {
   // General errors
   INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
   UNKNOWN_ERROR: "UNKNOWN_ERROR",
   VALIDATION_ERROR: "VALIDATION_ERROR",
   BAD_REQUEST: "BAD_REQUEST",
   TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

   // Authentication / Authorization
   UNAUTHORIZED: "UNAUTHORIZED",
   FORBIDDEN: "FORBIDDEN",
   TOKEN_EXPIRED: "TOKEN_EXPIRED",
   INVALID_TOKEN: "INVALID_TOKEN",

   // Resource-related
   NOT_FOUND: "NOT_FOUND",
   RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
   DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

   // User-specific
   USER_NOT_FOUND: "USER_NOT_FOUND",
   USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
   INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

   // Database / Server
   DATABASE_ERROR: "DATABASE_ERROR",
   CONNECTION_FAILED: "CONNECTION_FAILED",
   TIMEOUT_ERROR: "TIMEOUT_ERROR",
};
