/**
 *
 * *  Error Constants
 *
 */

// Error codes
export const ERROR_CODES = {
   // Authentication errors
   INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
   UNAUTHORIZED: "UNAUTHORIZED",
   FORBIDDEN: "FORBIDDEN",
   TOKEN_EXPIRED: "TOKEN_EXPIRED",
   TOKEN_INVALID: "TOKEN_INVALID",

   // Validation errors
   VALIDATION_ERROR: "VALIDATION_ERROR",
   REQUIRED_FIELD: "REQUIRED_FIELD",
   INVALID_EMAIL: "INVALID_EMAIL",
   INVALID_PHONE: "INVALID_PHONE",

   // Business logic errors
   USER_EXISTS: "USER_EXISTS",
   HOTEL_EXISTS: "HOTEL_EXISTS",
   ROOM_UNAVAILABLE: "ROOM_UNAVAILABLE",
   INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",

   // System / external errors
   DATABASE_ERROR: "DATABASE_ERROR",
   EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
   RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
};
